Revert "Fixed compilation error: Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags"
This reverts commit 7b35884b345c1c0ae748fb9c6547dba8f7571630.